### ISSUE TITLE
Dependancies not listed

### ISSUE THREAD

**Issue by CaptainYarb** [SpiGetOrg/RestAPI#2]
This php app doesn't include a list of dependencies, which makes contributing a little cumbersome. It's difficult to know what versions of your dependencies you're using (such as slim). As a recommendation using something like Composer would make this much easier.

**Comment by InventivetalentDev** [comment]
#5 Updated dependencies to composer & added [composer.json](https://github.com/SpiGetOrg/RestAPI/blob/master/composer.json)

**Comment by CaptainYarb** [comment]
Thank you! :D
