### ISSUE TITLE
<resource>/download should follow external download links

### ISSUE THREAD

**Issue by Phoenix616** [SpiGetOrg/RestAPI#8]
If you try to download a file from a resource that links to an external download it will claim that no file was found. It would be nice to redirect to the external link instead.

Optionally this could also filter the external links to only redirect to ones that seem to actually link to files (ending in .jar/.zip) to not try to download some site although such a filter would be really error prone (e.g. with sites like Dropbox and Mediafire lying about the type of the response)

**Comment by InventivetalentDev** [comment]
You can use `/:resource/versions/latest/download` to be redirected to the download location SpigotMC saved (internal or external).
You can also check the `external` field in the resource response to decide which route to use for the download.  

The whole reason behind this is the fact that SpigotMC is protected by CloudFlare, which makes automatic downloads quite difficulty. Therefore SpiGet downloads & caches the latest version, available at `/:resource/download`.  
The individual version download routes only redirect to the source link, but it's then up to the user to get around CloudFlare.
